
//*************************************************************************************
//   !!! Generated by the fmp-cli.  DO NOT EDIT!
//*************************************************************************************

public abstract class BucketUnitTestBase : IClassFixture<TestFixture>
{
    /// <summary>
    /// ╡Бйтиообнд
    /// </summary>
    protected TestFixture fixture_ { get; set; }

    public BucketUnitTestBase(TestFixture _testFixture)
    {
        fixture_ = _testFixture;
    }

    [Fact]
    public abstract Task MakeTest();

    [Fact]
    public abstract Task ListTest();

    [Fact]
    public abstract Task RemoveTest();

    [Fact]
    public abstract Task GetTest();

    [Fact]
    public abstract Task FindTest();

    [Fact]
    public abstract Task SearchTest();

    [Fact]
    public abstract Task UpdateTest();

    [Fact]
    public abstract Task ResetTokenTest();

    [Fact]
    public abstract Task GenerateManifestTest();

    [Fact]
    public abstract Task CleanTest();

}
