
//*************************************************************************************
//   !!! Generated by the fmp-cli.  DO NOT EDIT!
//*************************************************************************************

public class DAOManager<T>
{
    private static T? dao_ { get; set; }

    public static T Value
    {
        get
        {
            if (null == dao_)
            {
                var instance = Activator.CreateInstance(typeof(T), new DatabaseOptions());
                if(null != instance)
                    dao_ = (T)instance;
            }
            return dao_!;
        }
    }
}
