
//*************************************************************************************
//   !!! Generated by the fmp-cli.  DO NOT EDIT!
//*************************************************************************************

public abstract class HealthyUnitTestBase
{

    [Fact]
    public abstract Task EchoTest();

}
