
//*************************************************************************************
//   !!! Generated by the fmp-cli.  DO NOT EDIT!
//*************************************************************************************

public abstract class ObjectUnitTestBase
{

    [Fact]
    public abstract Task PrepareTest();

    [Fact]
    public abstract Task FlushTest();

    [Fact]
    public abstract Task GetTest();

    [Fact]
    public abstract Task FindTest();

    [Fact]
    public abstract Task RemoveTest();

    [Fact]
    public abstract Task ListTest();

    [Fact]
    public abstract Task SearchTest();

    [Fact]
    public abstract Task PublishTest();

    [Fact]
    public abstract Task PreviewTest();

    [Fact]
    public abstract Task RetractTest();

    [Fact]
    public abstract Task ConvertFromBase64Test();

    [Fact]
    public abstract Task ConvertFromUrlTest();

}
