//*************************************************************************************
//   !!! Generated by the fmp-cli.  DO NOT EDIT!
//*************************************************************************************
using XTC.FMP.MOD.File.App.Service;

public abstract class TestFixtureBase : IDisposable
{
    public TestServerCallContext context { get; set; }

    public TestFixtureBase()
    {
        context = TestServerCallContext.Create();
    }

    public virtual void Dispose()
    {
        var options = new DatabaseOptions();
        var mongoClient = new MongoDB.Driver.MongoClient(options.Value.ConnectionString);
        mongoClient.DropDatabase(options.Value.DatabaseName);
    }

    protected BucketService? serviceBucket_ { get; set; }

    public BucketService getServiceBucket()
    {
        if(null == serviceBucket_)
        {
            newBucketService();
        }
        return serviceBucket_!;
    }

    /// <summary>
    /// 实例化服务
    /// </summary>
    /// <example>
    /// service{{service}}_ = new {{service}}Service(new {{service}}DAO(new DatabaseOptions()));
    /// </example>
    protected abstract void newBucketService();
}

