
//*************************************************************************************
//   !!! Generated by the fmp-cli.  DO NOT EDIT!
//*************************************************************************************

namespace XTC.FMP.MOD.File.App.Service
{
    /// <summary>
    /// 数据库设置
    /// </summary>
    public class DatabaseSettings
    {
        /// <summary>
        /// 驱动
        /// </summary>
        public string Driver { get; set; } = "MongoDB";

        /// <summary>
        /// 连接字符
        /// </summary>
        public string ConnectionString { get; set; } = null!;

        /// <summary>
        /// 数据库名
        /// </summary>
        public string DatabaseName { get; set; } = null!;
    }
}
