
//*************************************************************************************
//   !!! Generated by the fmp-cli.  DO NOT EDIT!
//*************************************************************************************

using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Bson.Serialization.IdGenerators;

namespace XTC.FMP.MOD.File.App.Service
{
    /// <summary>
    /// 数据实体
    /// </summary>
    /// <example>
    /// public class YourDAO : DAO<YourEntity>
    /// {
    ///     public YourDAO(IOptions<DBSettings> _settings) : base(_settings)
    ///     {
    ///     }
    /// }
    /// </example>
    public class Entity
    {
        /// <summary>
        /// 实体的唯一识别ID
        /// </summary>
        /// <remarks>
        /// 不使用ObjectId
        /// </remarks>
        [BsonId(IdGenerator = typeof(CombGuidGenerator))]
        public Guid? Uuid { get; set; }
    }
}
