
//*************************************************************************************
//   !!! Generated by the fmp-cli.  DO NOT EDIT!
//*************************************************************************************

using XTC.FMP.MOD.File.LIB.Proto;
using XTC.FMP.MOD.File.LIB.Bridge;

namespace XTC.FMP.MOD.File.LIB.MVCS
{

    public class BucketMakeRequestDTO : IDTO
    {
        public BucketMakeRequestDTO(BucketMakeRequest _message)
        {
            message = _message;    
        }
        public readonly BucketMakeRequest message;
    }



    public class BucketListRequestDTO : IDTO
    {
        public BucketListRequestDTO(BucketListRequest _message)
        {
            message = _message;    
        }
        public readonly BucketListRequest message;
    }



    public class BucketListResponseDTO : IDTO
    {
        public BucketListResponseDTO(BucketListResponse _message)
        {
            message = _message;    
        }
        public readonly BucketListResponse message;
    }



    public class BucketRemoveRequestDTO : IDTO
    {
        public BucketRemoveRequestDTO(BucketRemoveRequest _message)
        {
            message = _message;    
        }
        public readonly BucketRemoveRequest message;
    }



    public class BucketGetRequestDTO : IDTO
    {
        public BucketGetRequestDTO(BucketGetRequest _message)
        {
            message = _message;    
        }
        public readonly BucketGetRequest message;
    }



    public class BucketGetResponseDTO : IDTO
    {
        public BucketGetResponseDTO(BucketGetResponse _message)
        {
            message = _message;    
        }
        public readonly BucketGetResponse message;
    }



    public class BucketFindRequestDTO : IDTO
    {
        public BucketFindRequestDTO(BucketFindRequest _message)
        {
            message = _message;    
        }
        public readonly BucketFindRequest message;
    }



    public class BucketFindResponseDTO : IDTO
    {
        public BucketFindResponseDTO(BucketFindResponse _message)
        {
            message = _message;    
        }
        public readonly BucketFindResponse message;
    }



    public class BucketSearchRequestDTO : IDTO
    {
        public BucketSearchRequestDTO(BucketSearchRequest _message)
        {
            message = _message;    
        }
        public readonly BucketSearchRequest message;
    }



    public class BucketSearchResponseDTO : IDTO
    {
        public BucketSearchResponseDTO(BucketSearchResponse _message)
        {
            message = _message;    
        }
        public readonly BucketSearchResponse message;
    }



    public class BucketUpdateRequestDTO : IDTO
    {
        public BucketUpdateRequestDTO(BucketUpdateRequest _message)
        {
            message = _message;    
        }
        public readonly BucketUpdateRequest message;
    }



    public class BucketResetTokenRequestDTO : IDTO
    {
        public BucketResetTokenRequestDTO(BucketResetTokenRequest _message)
        {
            message = _message;    
        }
        public readonly BucketResetTokenRequest message;
    }



    public class BucketGenerateManifestRequestDTO : IDTO
    {
        public BucketGenerateManifestRequestDTO(BucketGenerateManifestRequest _message)
        {
            message = _message;    
        }
        public readonly BucketGenerateManifestRequest message;
    }



    public class BucketGenerateManifestResponseDTO : IDTO
    {
        public BucketGenerateManifestResponseDTO(BucketGenerateManifestResponse _message)
        {
            message = _message;    
        }
        public readonly BucketGenerateManifestResponse message;
    }



    public class BucketCleanRequestDTO : IDTO
    {
        public BucketCleanRequestDTO(BucketCleanRequest _message)
        {
            message = _message;    
        }
        public readonly BucketCleanRequest message;
    }



    public class HealthyEchoRequestDTO : IDTO
    {
        public HealthyEchoRequestDTO(HealthyEchoRequest _message)
        {
            message = _message;    
        }
        public readonly HealthyEchoRequest message;
    }



    public class HealthyEchoResponseDTO : IDTO
    {
        public HealthyEchoResponseDTO(HealthyEchoResponse _message)
        {
            message = _message;    
        }
        public readonly HealthyEchoResponse message;
    }



    public class ObjectPrepareRequestDTO : IDTO
    {
        public ObjectPrepareRequestDTO(ObjectPrepareRequest _message)
        {
            message = _message;    
        }
        public readonly ObjectPrepareRequest message;
    }



    public class ObjectPrepareResponseDTO : IDTO
    {
        public ObjectPrepareResponseDTO(ObjectPrepareResponse _message)
        {
            message = _message;    
        }
        public readonly ObjectPrepareResponse message;
    }



    public class ObjectFlushRequestDTO : IDTO
    {
        public ObjectFlushRequestDTO(ObjectFlushRequest _message)
        {
            message = _message;    
        }
        public readonly ObjectFlushRequest message;
    }



    public class ObjectPublishRequestDTO : IDTO
    {
        public ObjectPublishRequestDTO(ObjectPublishRequest _message)
        {
            message = _message;    
        }
        public readonly ObjectPublishRequest message;
    }



    public class ObjectPublishResponseDTO : IDTO
    {
        public ObjectPublishResponseDTO(ObjectPublishResponse _message)
        {
            message = _message;    
        }
        public readonly ObjectPublishResponse message;
    }



    public class ObjectPreviewRequestDTO : IDTO
    {
        public ObjectPreviewRequestDTO(ObjectPreviewRequest _message)
        {
            message = _message;    
        }
        public readonly ObjectPreviewRequest message;
    }



    public class ObjectPreviewResponseDTO : IDTO
    {
        public ObjectPreviewResponseDTO(ObjectPreviewResponse _message)
        {
            message = _message;    
        }
        public readonly ObjectPreviewResponse message;
    }



    public class ObjectRetractRequestDTO : IDTO
    {
        public ObjectRetractRequestDTO(ObjectRetractRequest _message)
        {
            message = _message;    
        }
        public readonly ObjectRetractRequest message;
    }



    public class ObjectGetRequestDTO : IDTO
    {
        public ObjectGetRequestDTO(ObjectGetRequest _message)
        {
            message = _message;    
        }
        public readonly ObjectGetRequest message;
    }



    public class ObjectGetResponseDTO : IDTO
    {
        public ObjectGetResponseDTO(ObjectGetResponse _message)
        {
            message = _message;    
        }
        public readonly ObjectGetResponse message;
    }



    public class ObjectFindRequestDTO : IDTO
    {
        public ObjectFindRequestDTO(ObjectFindRequest _message)
        {
            message = _message;    
        }
        public readonly ObjectFindRequest message;
    }



    public class ObjectFindResponseDTO : IDTO
    {
        public ObjectFindResponseDTO(ObjectFindResponse _message)
        {
            message = _message;    
        }
        public readonly ObjectFindResponse message;
    }



    public class ObjectRemoveRequestDTO : IDTO
    {
        public ObjectRemoveRequestDTO(ObjectRemoveRequest _message)
        {
            message = _message;    
        }
        public readonly ObjectRemoveRequest message;
    }



    public class ObjectListRequestDTO : IDTO
    {
        public ObjectListRequestDTO(ObjectListRequest _message)
        {
            message = _message;    
        }
        public readonly ObjectListRequest message;
    }



    public class ObjectListResponseDTO : IDTO
    {
        public ObjectListResponseDTO(ObjectListResponse _message)
        {
            message = _message;    
        }
        public readonly ObjectListResponse message;
    }



    public class ObjectSearchRequestDTO : IDTO
    {
        public ObjectSearchRequestDTO(ObjectSearchRequest _message)
        {
            message = _message;    
        }
        public readonly ObjectSearchRequest message;
    }



    public class ObjectSearchResponseDTO : IDTO
    {
        public ObjectSearchResponseDTO(ObjectSearchResponse _message)
        {
            message = _message;    
        }
        public readonly ObjectSearchResponse message;
    }



    public class ObjectConvertFromBase64RequestDTO : IDTO
    {
        public ObjectConvertFromBase64RequestDTO(ObjectConvertFromBase64Request _message)
        {
            message = _message;    
        }
        public readonly ObjectConvertFromBase64Request message;
    }



    public class ObjectConvertFromBase64ResponseDTO : IDTO
    {
        public ObjectConvertFromBase64ResponseDTO(ObjectConvertFromBase64Response _message)
        {
            message = _message;    
        }
        public readonly ObjectConvertFromBase64Response message;
    }



    public class ObjectConvertFromUrlRequestDTO : IDTO
    {
        public ObjectConvertFromUrlRequestDTO(ObjectConvertFromUrlRequest _message)
        {
            message = _message;    
        }
        public readonly ObjectConvertFromUrlRequest message;
    }



    public class ObjectConvertFromUrlResponseDTO : IDTO
    {
        public ObjectConvertFromUrlResponseDTO(ObjectConvertFromUrlResponse _message)
        {
            message = _message;    
        }
        public readonly ObjectConvertFromUrlResponse message;
    }



    public class StatusDTO : IDTO
    {
        public StatusDTO(Status _message)
        {
            message = _message;    
        }
        public readonly Status message;
    }



    public class BlankRequestDTO : IDTO
    {
        public BlankRequestDTO(BlankRequest _message)
        {
            message = _message;    
        }
        public readonly BlankRequest message;
    }



    public class BlankResponseDTO : IDTO
    {
        public BlankResponseDTO(BlankResponse _message)
        {
            message = _message;    
        }
        public readonly BlankResponse message;
    }



    public class UuidResponseDTO : IDTO
    {
        public UuidResponseDTO(UuidResponse _message)
        {
            message = _message;    
        }
        public readonly UuidResponse message;
    }



    public class BucketEntityDTO : IDTO
    {
        public BucketEntityDTO(BucketEntity _message)
        {
            message = _message;    
        }
        public readonly BucketEntity message;
    }



    public class ObjectEntityDTO : IDTO
    {
        public ObjectEntityDTO(ObjectEntity _message)
        {
            message = _message;    
        }
        public readonly ObjectEntity message;
    }



    public class Base64SourceDTO : IDTO
    {
        public Base64SourceDTO(Base64Source _message)
        {
            message = _message;    
        }
        public readonly Base64Source message;
    }



    public class UrlSourceDTO : IDTO
    {
        public UrlSourceDTO(UrlSource _message)
        {
            message = _message;    
        }
        public readonly UrlSource message;
    }



}
