
//*************************************************************************************
//   !!! Generated by the fmp-cli.  DO NOT EDIT!
//*************************************************************************************

using XTC.FMP.MOD.File.LIB.Proto;
using XTC.FMP.MOD.File.LIB.Bridge;

namespace XTC.FMP.MOD.File.LIB.MVCS
{

    public class BucketMakeRequestDTO : IDTO
    {
        public BucketMakeRequestDTO(BucketMakeRequest _value)
        {
            Value = _value;    
        }
        public readonly BucketMakeRequest Value;
    }



    public class BucketListRequestDTO : IDTO
    {
        public BucketListRequestDTO(BucketListRequest _value)
        {
            Value = _value;    
        }
        public readonly BucketListRequest Value;
    }



    public class BucketListResponseDTO : IDTO
    {
        public BucketListResponseDTO(BucketListResponse _value)
        {
            Value = _value;    
        }
        public readonly BucketListResponse Value;
    }



    public class BucketRemoveRequestDTO : IDTO
    {
        public BucketRemoveRequestDTO(BucketRemoveRequest _value)
        {
            Value = _value;    
        }
        public readonly BucketRemoveRequest Value;
    }



    public class BucketGetRequestDTO : IDTO
    {
        public BucketGetRequestDTO(BucketGetRequest _value)
        {
            Value = _value;    
        }
        public readonly BucketGetRequest Value;
    }



    public class BucketGetResponseDTO : IDTO
    {
        public BucketGetResponseDTO(BucketGetResponse _value)
        {
            Value = _value;    
        }
        public readonly BucketGetResponse Value;
    }



    public class BucketFindRequestDTO : IDTO
    {
        public BucketFindRequestDTO(BucketFindRequest _value)
        {
            Value = _value;    
        }
        public readonly BucketFindRequest Value;
    }



    public class BucketFindResponseDTO : IDTO
    {
        public BucketFindResponseDTO(BucketFindResponse _value)
        {
            Value = _value;    
        }
        public readonly BucketFindResponse Value;
    }



    public class BucketSearchRequestDTO : IDTO
    {
        public BucketSearchRequestDTO(BucketSearchRequest _value)
        {
            Value = _value;    
        }
        public readonly BucketSearchRequest Value;
    }



    public class BucketSearchResponseDTO : IDTO
    {
        public BucketSearchResponseDTO(BucketSearchResponse _value)
        {
            Value = _value;    
        }
        public readonly BucketSearchResponse Value;
    }



    public class BucketUpdateRequestDTO : IDTO
    {
        public BucketUpdateRequestDTO(BucketUpdateRequest _value)
        {
            Value = _value;    
        }
        public readonly BucketUpdateRequest Value;
    }



    public class BucketResetTokenRequestDTO : IDTO
    {
        public BucketResetTokenRequestDTO(BucketResetTokenRequest _value)
        {
            Value = _value;    
        }
        public readonly BucketResetTokenRequest Value;
    }



    public class BucketGenerateManifestRequestDTO : IDTO
    {
        public BucketGenerateManifestRequestDTO(BucketGenerateManifestRequest _value)
        {
            Value = _value;    
        }
        public readonly BucketGenerateManifestRequest Value;
    }



    public class BucketGenerateManifestResponseDTO : IDTO
    {
        public BucketGenerateManifestResponseDTO(BucketGenerateManifestResponse _value)
        {
            Value = _value;    
        }
        public readonly BucketGenerateManifestResponse Value;
    }



    public class BucketCleanRequestDTO : IDTO
    {
        public BucketCleanRequestDTO(BucketCleanRequest _value)
        {
            Value = _value;    
        }
        public readonly BucketCleanRequest Value;
    }



    public class HealthyEchoRequestDTO : IDTO
    {
        public HealthyEchoRequestDTO(HealthyEchoRequest _value)
        {
            Value = _value;    
        }
        public readonly HealthyEchoRequest Value;
    }



    public class HealthyEchoResponseDTO : IDTO
    {
        public HealthyEchoResponseDTO(HealthyEchoResponse _value)
        {
            Value = _value;    
        }
        public readonly HealthyEchoResponse Value;
    }



    public class ObjectPrepareRequestDTO : IDTO
    {
        public ObjectPrepareRequestDTO(ObjectPrepareRequest _value)
        {
            Value = _value;    
        }
        public readonly ObjectPrepareRequest Value;
    }



    public class ObjectPrepareResponseDTO : IDTO
    {
        public ObjectPrepareResponseDTO(ObjectPrepareResponse _value)
        {
            Value = _value;    
        }
        public readonly ObjectPrepareResponse Value;
    }



    public class ObjectFlushRequestDTO : IDTO
    {
        public ObjectFlushRequestDTO(ObjectFlushRequest _value)
        {
            Value = _value;    
        }
        public readonly ObjectFlushRequest Value;
    }



    public class ObjectPublishRequestDTO : IDTO
    {
        public ObjectPublishRequestDTO(ObjectPublishRequest _value)
        {
            Value = _value;    
        }
        public readonly ObjectPublishRequest Value;
    }



    public class ObjectPublishResponseDTO : IDTO
    {
        public ObjectPublishResponseDTO(ObjectPublishResponse _value)
        {
            Value = _value;    
        }
        public readonly ObjectPublishResponse Value;
    }



    public class ObjectPreviewRequestDTO : IDTO
    {
        public ObjectPreviewRequestDTO(ObjectPreviewRequest _value)
        {
            Value = _value;    
        }
        public readonly ObjectPreviewRequest Value;
    }



    public class ObjectPreviewResponseDTO : IDTO
    {
        public ObjectPreviewResponseDTO(ObjectPreviewResponse _value)
        {
            Value = _value;    
        }
        public readonly ObjectPreviewResponse Value;
    }



    public class ObjectRetractRequestDTO : IDTO
    {
        public ObjectRetractRequestDTO(ObjectRetractRequest _value)
        {
            Value = _value;    
        }
        public readonly ObjectRetractRequest Value;
    }



    public class ObjectGetRequestDTO : IDTO
    {
        public ObjectGetRequestDTO(ObjectGetRequest _value)
        {
            Value = _value;    
        }
        public readonly ObjectGetRequest Value;
    }



    public class ObjectGetResponseDTO : IDTO
    {
        public ObjectGetResponseDTO(ObjectGetResponse _value)
        {
            Value = _value;    
        }
        public readonly ObjectGetResponse Value;
    }



    public class ObjectFindRequestDTO : IDTO
    {
        public ObjectFindRequestDTO(ObjectFindRequest _value)
        {
            Value = _value;    
        }
        public readonly ObjectFindRequest Value;
    }



    public class ObjectFindResponseDTO : IDTO
    {
        public ObjectFindResponseDTO(ObjectFindResponse _value)
        {
            Value = _value;    
        }
        public readonly ObjectFindResponse Value;
    }



    public class ObjectRemoveRequestDTO : IDTO
    {
        public ObjectRemoveRequestDTO(ObjectRemoveRequest _value)
        {
            Value = _value;    
        }
        public readonly ObjectRemoveRequest Value;
    }



    public class ObjectListRequestDTO : IDTO
    {
        public ObjectListRequestDTO(ObjectListRequest _value)
        {
            Value = _value;    
        }
        public readonly ObjectListRequest Value;
    }



    public class ObjectListResponseDTO : IDTO
    {
        public ObjectListResponseDTO(ObjectListResponse _value)
        {
            Value = _value;    
        }
        public readonly ObjectListResponse Value;
    }



    public class ObjectSearchRequestDTO : IDTO
    {
        public ObjectSearchRequestDTO(ObjectSearchRequest _value)
        {
            Value = _value;    
        }
        public readonly ObjectSearchRequest Value;
    }



    public class ObjectSearchResponseDTO : IDTO
    {
        public ObjectSearchResponseDTO(ObjectSearchResponse _value)
        {
            Value = _value;    
        }
        public readonly ObjectSearchResponse Value;
    }



    public class ObjectConvertFromBase64RequestDTO : IDTO
    {
        public ObjectConvertFromBase64RequestDTO(ObjectConvertFromBase64Request _value)
        {
            Value = _value;    
        }
        public readonly ObjectConvertFromBase64Request Value;
    }



    public class ObjectConvertFromBase64ResponseDTO : IDTO
    {
        public ObjectConvertFromBase64ResponseDTO(ObjectConvertFromBase64Response _value)
        {
            Value = _value;    
        }
        public readonly ObjectConvertFromBase64Response Value;
    }



    public class ObjectConvertFromUrlRequestDTO : IDTO
    {
        public ObjectConvertFromUrlRequestDTO(ObjectConvertFromUrlRequest _value)
        {
            Value = _value;    
        }
        public readonly ObjectConvertFromUrlRequest Value;
    }



    public class ObjectConvertFromUrlResponseDTO : IDTO
    {
        public ObjectConvertFromUrlResponseDTO(ObjectConvertFromUrlResponse _value)
        {
            Value = _value;    
        }
        public readonly ObjectConvertFromUrlResponse Value;
    }



    public class StatusDTO : IDTO
    {
        public StatusDTO(Status _value)
        {
            Value = _value;    
        }
        public readonly Status Value;
    }



    public class BlankRequestDTO : IDTO
    {
        public BlankRequestDTO(BlankRequest _value)
        {
            Value = _value;    
        }
        public readonly BlankRequest Value;
    }



    public class BlankResponseDTO : IDTO
    {
        public BlankResponseDTO(BlankResponse _value)
        {
            Value = _value;    
        }
        public readonly BlankResponse Value;
    }



    public class UuidResponseDTO : IDTO
    {
        public UuidResponseDTO(UuidResponse _value)
        {
            Value = _value;    
        }
        public readonly UuidResponse Value;
    }



    public class StorageDTO : IDTO
    {
        public StorageDTO(Storage _value)
        {
            Value = _value;    
        }
        public readonly Storage Value;
    }



    public class BucketEntityDTO : IDTO
    {
        public BucketEntityDTO(BucketEntity _value)
        {
            Value = _value;    
        }
        public readonly BucketEntity Value;
    }



    public class ObjectEntityDTO : IDTO
    {
        public ObjectEntityDTO(ObjectEntity _value)
        {
            Value = _value;    
        }
        public readonly ObjectEntity Value;
    }



    public class Base64SourceDTO : IDTO
    {
        public Base64SourceDTO(Base64Source _value)
        {
            Value = _value;    
        }
        public readonly Base64Source Value;
    }



    public class UrlSourceDTO : IDTO
    {
        public UrlSourceDTO(UrlSource _value)
        {
            Value = _value;    
        }
        public readonly UrlSource Value;
    }



}
