
//*************************************************************************************
//   !!! Generated by the fmp-cli.  DO NOT EDIT!
//*************************************************************************************

using XTC.FMP.LIB.MVCS;

namespace XTC.FMP.MOD.File.LIB.Bridge
{
    /// <summary>
    /// Bucket的UI桥接层（协议部分）
    /// 刷新从视图收到的数据
    /// </summary>
    public interface IBucketUiProtoBridge : View.Facade.Bridge
    {
        /// <summary>
        /// 全局警告
        /// </summary>
        /// <param name="_code">错误码</param>
        /// <param name="_code">错误信息</param>
        void Alert(string _code, string _message);

        /// <summary>
        /// 刷新Make的数据
        /// </summary>
        void RefreshMake(IDTO _dto);


        /// <summary>
        /// 刷新List的数据
        /// </summary>
        void RefreshList(IDTO _dto);


        /// <summary>
        /// 刷新Remove的数据
        /// </summary>
        void RefreshRemove(IDTO _dto);


        /// <summary>
        /// 刷新Get的数据
        /// </summary>
        void RefreshGet(IDTO _dto);


        /// <summary>
        /// 刷新Find的数据
        /// </summary>
        void RefreshFind(IDTO _dto);


        /// <summary>
        /// 刷新Search的数据
        /// </summary>
        void RefreshSearch(IDTO _dto);


        /// <summary>
        /// 刷新Update的数据
        /// </summary>
        void RefreshUpdate(IDTO _dto);


        /// <summary>
        /// 刷新ResetToken的数据
        /// </summary>
        void RefreshResetToken(IDTO _dto);


        /// <summary>
        /// 刷新GenerateManifest的数据
        /// </summary>
        void RefreshGenerateManifest(IDTO _dto);


        /// <summary>
        /// 刷新Clean的数据
        /// </summary>
        void RefreshClean(IDTO _dto);


    }
}

