
//*************************************************************************************
//   !!! Generated by the fmp-cli.  DO NOT EDIT!
//*************************************************************************************

using System.Threading.Tasks;
using XTC.FMP.LIB.MVCS;

namespace XTC.FMP.MOD.File.LIB.Bridge
{
    /// <summary>
    /// Object的视图桥接层（协议部分）
    /// 处理UI的事件
    /// </summary>
    public interface IObjectViewProtoBridge : View.Facade.Bridge
    {

        /// <summary>
        /// 处理Prepare的提交
        /// </summary>
        Task<Error> OnPrepareSubmit(IDTO _dto);


        /// <summary>
        /// 处理Flush的提交
        /// </summary>
        Task<Error> OnFlushSubmit(IDTO _dto);


        /// <summary>
        /// 处理Get的提交
        /// </summary>
        Task<Error> OnGetSubmit(IDTO _dto);


        /// <summary>
        /// 处理Find的提交
        /// </summary>
        Task<Error> OnFindSubmit(IDTO _dto);


        /// <summary>
        /// 处理Remove的提交
        /// </summary>
        Task<Error> OnRemoveSubmit(IDTO _dto);


        /// <summary>
        /// 处理List的提交
        /// </summary>
        Task<Error> OnListSubmit(IDTO _dto);


        /// <summary>
        /// 处理Search的提交
        /// </summary>
        Task<Error> OnSearchSubmit(IDTO _dto);


        /// <summary>
        /// 处理Publish的提交
        /// </summary>
        Task<Error> OnPublishSubmit(IDTO _dto);


        /// <summary>
        /// 处理Preview的提交
        /// </summary>
        Task<Error> OnPreviewSubmit(IDTO _dto);


        /// <summary>
        /// 处理Retract的提交
        /// </summary>
        Task<Error> OnRetractSubmit(IDTO _dto);


        /// <summary>
        /// 处理ConvertFromBase64的提交
        /// </summary>
        Task<Error> OnConvertFromBase64Submit(IDTO _dto);


        /// <summary>
        /// 处理ConvertFromUrl的提交
        /// </summary>
        Task<Error> OnConvertFromUrlSubmit(IDTO _dto);


    }
}

