
//*************************************************************************************
//   !!! Generated by the fmp-cli.  DO NOT EDIT!
//*************************************************************************************

using XTC.FMP.LIB.MVCS;

namespace XTC.FMP.MOD.File.LIB.Bridge
{
    /// <summary>
    /// Object的UI桥接层（协议部分）
    /// 刷新从视图收到的数据
    /// </summary>
    public interface IObjectUiProtoBridge : View.Facade.Bridge
    {
        /// <summary>
        /// 全局警告
        /// </summary>
        /// <param name="_code">错误码</param>
        /// <param name="_code">错误信息</param>
        void Alert(string _code, string _message);

        /// <summary>
        /// 刷新Prepare的数据
        /// </summary>
        void RefreshPrepare(IDTO _dto);


        /// <summary>
        /// 刷新Flush的数据
        /// </summary>
        void RefreshFlush(IDTO _dto);


        /// <summary>
        /// 刷新Get的数据
        /// </summary>
        void RefreshGet(IDTO _dto);


        /// <summary>
        /// 刷新Find的数据
        /// </summary>
        void RefreshFind(IDTO _dto);


        /// <summary>
        /// 刷新Remove的数据
        /// </summary>
        void RefreshRemove(IDTO _dto);


        /// <summary>
        /// 刷新List的数据
        /// </summary>
        void RefreshList(IDTO _dto);


        /// <summary>
        /// 刷新Search的数据
        /// </summary>
        void RefreshSearch(IDTO _dto);


        /// <summary>
        /// 刷新Publish的数据
        /// </summary>
        void RefreshPublish(IDTO _dto);


        /// <summary>
        /// 刷新Preview的数据
        /// </summary>
        void RefreshPreview(IDTO _dto);


        /// <summary>
        /// 刷新Retract的数据
        /// </summary>
        void RefreshRetract(IDTO _dto);


        /// <summary>
        /// 刷新ConvertFromBase64的数据
        /// </summary>
        void RefreshConvertFromBase64(IDTO _dto);


        /// <summary>
        /// 刷新ConvertFromUrl的数据
        /// </summary>
        void RefreshConvertFromUrl(IDTO _dto);


    }
}

